= Spring Boot Demo of javaslang-circuitbreaker

This demo shows how to use the fault tolerance library https://github.com/RobWin/javaslang-circuitbreaker[javaslang-circuitbreaker] in a Spring Boot application.

The demo shows how to use a custom Spring AOP Aspect `CircuitBreakerAspect` and a custom `CircuitBreaker` annotation to make your Spring Boot application more fault tolerant. You can either annotate a class in order to protect all public methods or just some specific methods.
For example:

[source,java]
----
@CircuitBreaker(backend = "backendA")
@Component(value = "backendAConnector")
public class BackendAConnector implements Connector {
    ...
}
----

Spring Boot Actuator health information can be used to check the status of your running application. It is often used by monitoring software to alert someone if a production system has serious issues. This demo publishes the status and metrics of all CircuitBreakers via a custom `CircuitBreakerHealthIndicator`. A closed CircuitBreaker state is mapped to UP, an open state to DOWN and a half-open state to UNKNOWN.
For example:

[source,json]
----
{
  "status": "UP",
  "backendA": {
    "status": "DOWN",
    "failureRate": "60.0%",
    "failureRateThreshold": "50.0%",
    "maxBufferedCalls": 5,
    "bufferedCalls": 5,
    "failedCalls": 3,
    "notPermittedCalls": 0
  },
  "backendB": {
    "status": "UP",
    "failureRate": "0.0%",
    "failureRateThreshold": "50.0%",
    "maxBufferedCalls": 10,
    "bufferedCalls": 10,
    "failedCalls": 0,
    "notPermittedCalls": 0
  }
}
----

You can configure your CircuitBreakers in Spring Boot's `application.yml` config file.
For example

----
circuitbreaker:
    backends:
        backendA:
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitInterval: 5000
            failureRateThreshold: 50
        backendB:
            ringBufferSizeInClosedState: 10
            ringBufferSizeInHalfOpenState: 5
            waitInterval: 5000
            failureRateThreshold: 50
----

The demo adds a custom Spring Boot Actuator endpoint which can be used to monitor the emitted events of your CircuitBreakers.
The endpoint `/management/circuitbreaker` lists the names of all CircuitBreaker instances.
For example:

----
[
  "backendA",
  "backendB"
]
----

The endpoint `/management/circuitbreaker/events` list the latest 100 emitted events of a all CircuitBreaker instances.

----
[
  "2017-01-10T14:24:59.160+01:00[Europe/Berlin]: CircuitBreaker 'backendA' recorded a successful call. Elapsed time: 0 ms",
  "2017-01-10T14:25:00.237+01:00[Europe/Berlin]: CircuitBreaker 'backendA' recorded an error: 'org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception'. Elapsed time: 0 ms",
  "2017-01-10T14:25:07.220+01:00[Europe/Berlin]: CircuitBreaker 'backendB' recorded an error: 'org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception'. Elapsed time: 0 ms",
  "2017-01-10T14:25:08.385+01:00[Europe/Berlin]: CircuitBreaker 'backendB' recorded a successful call. Elapsed time: 0 ms"
]
----

The endpoint `/management/circuitbreaker/events/{circuitBreakerName}` lists the latest emitted events of a specific CircuitBreaker.
For example `/management/circuitbreaker/events/backendA`:

----
[
  "2017-01-10T13:00:06.007+01:00[Europe/Berlin]: CircuitBreaker 'backendA' recorded an error: 'org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception'. Elapsed time: 0 ms",
  "2017-01-10T13:00:07.314+01:00[Europe/Berlin]: CircuitBreaker 'backendA' recorded a successful call. Elapsed time: 0 ms",
  "2017-01-10T13:00:13.909+01:00[Europe/Berlin]: CircuitBreaker 'backendA' recorded an error: 'org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception'. Elapsed time: 0 ms",
  "2017-01-10T13:00:14.932+01:00[Europe/Berlin]: CircuitBreaker 'backendA' recorded a successful call. Elapsed time: 0 ms"
]
----

You can even filter the list of  events.
The endpoint `/management/circuitbreaker/events/{circuitBreakerName}/{eventType}` lists the filtered events.
Event types can be:

* ERROR: A CircuitBreakerEvent which informs that an error has been recorded.
* IGNORED_ERROR: A CircuitBreakerEvent which informs that an error has been ignored.
* SUCCESS: A CircuitBreakerEvent which informs that a success has been recorded.
* NOT_PERMITTED: A CircuitBreakerEvent which informs that a call was not permitted because the CircuitBreaker state is OPEN.
* STATE_TRANSITION: A CircuitBreakerEvent which informs the state of the CircuitBreaker has been changed.

For example `/management/circuitbreaker/events/backendA/ERROR`:
----
[
  "2017-01-10T13:00:06.007+01:00[Europe/Berlin]: CircuitBreaker 'backendA' recorded an error: 'org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception'. Elapsed time: 0 ms",
  "2017-01-10T13:00:13.909+01:00[Europe/Berlin]: CircuitBreaker 'backendA' recorded an error: 'org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception'. Elapsed time: 0 ms",
]
----